graph TB
  A[Add Readme and restrictive license]-->B[Setup manuscript structure]
  B-->C[Methods: Describe study design]
  C-->D[Methods: Describe apparatus]
  D-->E[Methods: Describe procedure]
  E-->F[Bibliography: Add literature about more conservative method]
  E-->G[Bibliography: Add literature about more progressive method]
  F-->H[Introduction: Explain and reference conservative method]
  G-->I[Introduction: Explain and reference progressive method]
  I-->J[Methods: Rewrite around progressive method]
  H-->K[Choose progressive method, but mention both in introduction]
  J-->K
