# Workflow

After learning to explore existing git repos, being productive with git is the next objective.
This chapter describes the workflow of integrating your changes into a new or existing project.

## Setup

Before you create your first commits, you have to configure a few settings:

Commit identity
: Your name and email address you want to be associated with your commits

Editor
: The text editor that should be opened when Git asks you for text input, e.g., commit messages.

Default initial branch
: The default name of a branch initially created after a new repo has been created.

Git has a subcommand named `git config` which is used to customize Git's behavior on your local machine via settings.
There are many settings, and a setting can be configured for a single repo,
or as a (global) user default which is used for every repo where this setting isn't configured.
Here we will just set some user default settings.
Config settings are never persisted to the history or shared with collaborators, because they customize your working environment.
Git Tower doesn't provide a full interface to the config settings, and you partially need the command line.

```bash
# Display full user config
git config --global -l
# Display local repo config with merged global config
git config -l
```

### Commit identity

This identity is persisted into each of your commits and visible for everyone who can see your commits, thus it should be properly set.
It's just descriptive metadata, Git itself doesn't verify your email.
The actual identity data becomes more critical in conjunction with hosting platforms like Github or Gitlab,
because the platforms offer more security features and use the email to attribute your commits to your platform account.
Github provides [anonymized email addresses][github-commit-email] for users who don't want to expose their personal email.

In Git Tower, you can configure your user name and email via Preferences -> Git Config.
As a convenience feature provided by Git Tower, you can also store multiple identities under Preferences -> User Profiles, e.g., for work and private commits.
On the command line, use these commands to configure your identity:

```bash
# Please replace the identity values with your identity
git config --global user.name "Tamara Cook, M.Sc."
git config --global user.email tamara.cook@uni-marburg.de
# To display the current values, execute without second argument
git config --global user.name
git config --global user.email
```

### Editor

Git needs the program path of your preferred text editor.
When Git asks for text input, it opens this editor in a special mode where you can enter text,
and Git waits until you confirm your input by saving and closing the document.
In Git Tower, this setting will rarely be used.
If you'd never use the command line, you could skip this step, but it is recommended as a precaution.
Please configure one of the editors listed [in this appendix of Git Pro][editor-config] (table 4).

### Default initial branch

When a new repository is created, Git also creates an initial branch as a starting point to work with immediately.
This branch often represents the current stable version of the project and is set as HEAD on hosting platforms like Gitlab or Github.
This affects the active branch after cloning a repo, and how a repo is displayed on the web page.
Historically, it's default name has been “master”, but a cultural change has occurred in the tech community
which strives to replace the master/slave terms in technical speech with more neutral and politically inclusive ones.
Git and platforms like Gitlab and Github support this movement and have chosen “main” as the new default name for initial branches.
The migration process is inevitable but still in progress,
that's why explicitly configuring the default name via user config setting is part of the first git setup for the time being:

```bash
# Create new repos with a initial branch called main
git config --global init.defaultBranch main
```

## Creating a git repository

A repository is just a hidden _.git_ directory in the working copy root,
and Git can add a pristine repository to any physical directory, be it empty or an existing project.
This pristine state of the new repository can be viewed as the root of the history graph, a virtual zero commit.
Afterwards, Git automatically creates and activates an initial branch one can immediately work with.

### Git Tower

1. Go to Repositories view and hit “Create new local repository” in context menu.
2. Create a new directory or choose an existing one where you want to create a Git repository.
3. The new repository is added to the Repositories view.

### Command line

1. Create a new directory or choose an existing one that you want to turn into a Git repository.
2. Open a terminal in this directory.
3. Create a new git repository by running `git init`.

### Hosting platform

If you want to connect your repo with a hosting platform, you have to create a new repository on the respective platform.
Please look for “Create new repository” or similar functions.
You'll be asked for some metadata and to set the repo name and group which determines the repo URL.
You have two alternative strategies for the actual git repo:

1. Let the platform initialize the repo and clone it afterwards.
   This is appropriate for creating completely new projects.
2. Skip initializing, add the new URL as remote to an existing local repo, and push the initial branch.
   If you want to populate an existing local repo, or need more control over the initialization process, this is the right choice.

## Creating new commits

We already know that a new commit contains the differences to the currently active commit (HEAD), and that the new commit becomes HEAD after it has been created.
So the standard workflow is creating a sequence of commits during work.
Creating commits is an iterative explicit workflow which may need some habit building,
but can be a tool for structuring one's thoughts and making work results visible.

- Edit your working copy
- View and select changes in the working copy compared to the current HEAD
- Create new commit

### Editing the working copy

This is your actual work with you usual productivity tools.
Your project folder contains a (maybe still pristine) copy of HEAD,
and here you can make your improvements.
Physical files and lines can be added, modified, and deleted.
After you have finished a task or something similar that can be suitable for a commit, it's time to proceed to the next step.

### Viewing and selecting changes in the working copy

Git doesn't track the user's working actions,
but it just compares the working copy to HEAD and shows the differences in the diff format you have already seen in the history section.
This differential approach is an important building block which makes Git tool agnostic.
It can be helpful to imagine this as an additional virtual location where the unversioned changes are collected in a change set.
The change set depends on the working copy, and it is a good habit to observe the change set during work.
If you select and commit some changes, these changes disappear from the change set and flow into the history where they become versioned.

`r mermaid::mermaid("../diagrams/data-flow.mmd")`

In Git Tower, the Working copy view is made for preparing and creating commits.
The Tower help provides overview sections about [inspecting changes] and [selecting changes].

You can select either complete files via checkbox, or partial files where a change occurred.
If you are sure that you want to select everything, simply hit the “Stage all” button and you are ready to commit.
Noticeably, Git has weird terms for many usual concepts, and staging is the term for selecting changes for the next commit.

On the command line, Git provides some subcommands for viewing and selecting changes:

- `git status` lists the changed files.
- `git diff <filepath>` shows the diff view of the given file.
- `git add <filepath>` stages a file.
- `git restore --staged <filepath>` unstages a file.

The status output differentiates between tracked files and untracked files:

- Tracked files were already committed to the history, but the working copy contains added or deleted lines.
- Untracked files were never committed before, but staging and committing them adds them to the history which turns them into tracked files.

You might also be interested in [interactive staging] by Git Pro for the partial file selection.

### Creating a new commit

This is the transition of the selected changes into the history.
After figuring out your change selection, enter a well-formed commit message, and hit Commit.
The committed changes are now versioned and should disappear from the change list.

On the command line, execute `git commit` to create a commit from the selection.
Your text editor will open and wait for the commit message being saved.
You can also run `git commit -m "My non-interactive message"` to skip the editor step.

## Populating the working copy

If we want to work on another branch or change HEAD for another reason,
we would possibly see many pointless changes in the change set.
we need a way to restore history commits to the working copy.
Git offers the `checkout` command to synchronize the working copy with the history.
This command actually throws two concepts together (switch HEAD and restore files), that's why its usage can be a bit confusing.
Please examine your change set always before using checkout, because unversioned changes can get lost or Git will refuse to checkout.

- Checking out a file means keeping HEAD as is, and just restoring the files in the given path from the HEAD commit.
  This is commonly used for discarding unversioned changes.
- Checking out a branch, tag, or commit means setting HEAD to that commit, and overwriting the working copy with the state corresponding to HEAD.
  This should only be done if the working copy is clean.
- You will encounter the checkout command in many more circumstances, because it has a pletora of shortcut options.

```bash
# Restore the complete project from HEAD
git checkout .
# Checkout file from HEAD
git checkout README.md
# Restore files in path from HEAD
git checkout source/*
# Checkout the main branch
git checkout main
# Checkout the abc commit
git checkout abc
```

If you commit after a successful checkout, a diverging tree will be the result.

## Creating branches and tags

In your own repos, you will need to create your own branches and tags.
Git provides a couple of commands to cover various scenarios.

```bash
# Create a branch named testing which points to the HEAD commit
git branch testing
# Create an annotated tag named v0.1.0 pointing to HEAD
# This is part of the git tree
git tag -a v0.1.0
# Create a tag named latest which points to the HEAD commit
# This marks v0.1.0 as latest release
git tag latest
# Create a branch named feature which points to latest tag
git branch feature latest
# Combine creating a branch with checkout
# Create and checkout a branch named develop pointing to HEAD
git checkout -b develop
# Create and checkout a branch named fix pointing to main
git checkout -b fix main
```

[editor-config]: https://www.git-scm.com/book/en/v2/Appendix-C%3A-Git-Commands-Setup-and-Config#ch_core_editor
[github-commit-email]: https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address
[inspecting changes]: https://www.git-tower.com/help/guides/working-copy/inspect-changes
[selecting changes]: https://www.git-tower.com/help/guides/working-copy/stage-changes
[interactive-staging]: https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging
