---
title: Version Control with Git
author: Tamara Cook, M.Sc[^affiliation]
date: 29.06.2021
lang: en-US
documentclass: scrreprt
bibliography: ../references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
biblio-style: apa
biblatexoptions: [backend=biber]
nocite: |
  @Chacon:2014aa
---

[^affiliation]:
    Philipps-Universität Marburg\
    Fachbereich Psychologie (FB06)\
    AG Allgemeine und Biologische Psychologie\
    Email: [tamara.cook@uni-marburg.de](mailto:tamara.cook@uni-marburg.de)

# Welcome {-}

You are visiting the written version of a course about integrating version control using Git into research projects.
This course was initially created for the members of the [CRC 135][sfb135] and their scientific staff within the CRC's [NOWA] project.

## Overview

The course is divided into two parts:

1. Concepts of version control and basic workflows
2. Project customization and collaboration

### Concepts of version control and basic workflows

In this session, the participants familiarize themselves with version control as a working method and get the opportunity to practice the basic Git workflows.
They will be able to:

- Explore existing Git repositories, browse the version history, compare versions, extract data from older versions
- Edit data in a repo and add new versions,, make use of Git's features for parallel working contexts
- Decide if Git is suitable for their needs

### Project customization and Gitlab

In this session, the scope extends to collaboration on Gitlab projects. These topics are covered:

- Connecting Git repos with Gitlab and uploading work for backup
- Customizing Git repos for the project content
- Sharing Gitlab projects with co-workers for review
- Collaborating with co-workers on a shared Gitlab project

[sfb135]: https://www.allpsych.uni-giessen.de/sfb/
[nowa]: https://www.allpsych.uni-giessen.de/sfb/projekte/inf.html
