name: renderbook and deploy
on:
  push:
    branches:
      - main
jobs:
  bookdown:
    name: Build handout page
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown", "DiagrammeR"), type = "binary", repos = "https://packagemanager.rstudio.com/all/latest")'
      - name: Render Bookdown files
        run: Rscript -e 'bookdown::render_book("source/handout", output_format = "bookdown::gitbook")'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
